name: Feature request
description: Propose a new feature for frontend, backend, or contracts
labels: ["type:feature"]
body:
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - frontend
        - backend
        - contracts
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem are we solving?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the approach and what needs to change.
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Bullet list of verifiable outcomes.
    validations:
      required: true
  - type: textarea
    id: definition_of_done
    attributes:
      label: Definition of Done
      description: What should be true at the end of this issue? Include tests/docs.
    validations:
      required: true
